modLoader="javafml" #mandatory

loaderVersion="[37,)" #mandatory (36 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="greater_eye" #mandatory
version="1.2.1" #mandatory
displayName="GreaterEye" #mandatory
description='''
An improvement on the Eye of Ender
'''


[[dependencies.greater_eye]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.greater_eye]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
