modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="greater_eye" #mandatory
version="1.1.3" #mandatory
displayName="GreaterEye" #mandatory
description='''
An improvement on the Eye of Ender
'''


[[dependencies.greater_eye]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.greater_eye]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.16.3]"
    ordering="NONE"
    side="BOTH"
